[package]
name = "i3-status-info"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4.2.2", features=["derive"]}
sysinfo = "0.28.4"
procfs = "0.15.1"
ping = "0.4.1"